USE airbound_app;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS readings;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS sensor_data;
DROP TABLE IF EXISTS predictions;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE devices (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(160) NOT NULL,
  api_key VARCHAR(64) NOT NULL UNIQUE,
  lat DECIMAL(10,6) DEFAULT NULL,
  lng DECIMAL(10,6) DEFAULT NULL,
  last_seen INT UNSIGNED DEFAULT NULL,
  status ENUM('online','offline') DEFAULT 'offline',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE readings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  device_id INT UNSIGNED NOT NULL,
  pm25 DECIMAL(8,3) DEFAULT NULL,
  pm10 DECIMAL(8,3) DEFAULT NULL,
  co DECIMAL(10,4) DEFAULT NULL,
  no2 DECIMAL(8,3) DEFAULT NULL,
  raw JSON DEFAULT NULL,
  created_at INT UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  INDEX (device_id),
  CONSTRAINT fk_readings_device FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  device_id INT UNSIGNED NOT NULL,
  reading_id BIGINT UNSIGNED DEFAULT NULL,
  pollutant VARCHAR(16) DEFAULT NULL,
  value DOUBLE DEFAULT NULL,
  unit VARCHAR(16) DEFAULT NULL,
  level VARCHAR(32) NOT NULL,
  icon VARCHAR(8) DEFAULT NULL,
  color VARCHAR(32) DEFAULT NULL,
  message TEXT,
  lat DOUBLE DEFAULT NULL,
  lng DOUBLE DEFAULT NULL,
  created_at INT NOT NULL,
  read_at INT DEFAULT NULL,
  resolved_at INT DEFAULT NULL,
  FOREIGN KEY (device_id) REFERENCES devices(id) ON DELETE CASCADE,
  INDEX (created_at),
  INDEX (device_id),
  INDEX (pollutant)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE sensor_data (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  mq2 DOUBLE DEFAULT NULL,
  mq135 DOUBLE DEFAULT NULL,
  dust DOUBLE DEFAULT NULL,
  created_at INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  INDEX (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE predictions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  predicted_aqi VARCHAR(120) DEFAULT NULL,
  confidence DOUBLE DEFAULT NULL,
  prediction_time VARCHAR(64) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
